### PR TITLE
Fix requirements

### PR DESCRIPTION
**Pull request by tashrifbillah**

### CODE REVIEW

**Comment by tashrifbillah** [comment]
I have added separate library files for CPU and GPU. The PR is now complete.

**Comment by SaraRomanella** [comment]
Hi, I am sorry. I write here because of the error I am having may be due to requirements. I am running the whole segmentation and after the trials in coronal, axial, sagittal the process stops and it says it does not recognize the original MRI. The error above that is:

/home/osboxes/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0

Is there a specific NVIDIA I have to download and install? I am running fastsurfer on a linux on a Ubuntu. Thank you so much for any info you can give me!

**Comment by tashrifbillah** [comment]
Hello @SaraRomanella , are you getting an error with my pull request? If not, please consider opening a separate issue. Also, please post the command you tried and the complete error traceback.

**Comment by LeHenschel** [comment]
As explained in #17, requirements.txt is not the CPU version, but the GPU version for a wheel based installation. I now added two yml-files one for CPU and one for the GPU conda based installation. Therefore, I am going to close the pull request.

**Comment by tashrifbillah** [comment]
@LeHenschel , the work I did had both--`requirements.txt` for CPU and `environment_gpu.yml` for GPU. Here is the diff:
https://github.com/tashrifbillah/FastSurfer/commit/8c9c4c49b2506bb754dcd3028a175a65a6522c7d

If you would like to encourage collaboration on this software, it would be good to integrate people's work directly or at least credit them in the relevant commit. :)

**Pull request closed without merging**
