### PR TITLE
 Fix output type of N4 bias field correction and add uchar flag

### LINKED ISSUE #461: N4 bias field correction without rescaling also converts to UCHAR
## Description
In recon_surf/N4_bias_correct.py if it is called to output the --outvol, but the input is not UCHAR (i.e. the mean is not around 150 or so) the script renormalizes the input to the old mean (of the input image). After that, it is converted to UCHAR by clamping, so all intensity information >255 is lost. This is not an expected behavior.

## Steps to Reproduce
Run N4_bias_correct on an image that is not UCHAR / not conformed.

## Expected Behavior
Retains data type, or additional flag for conforming intensities.

### PR DESCRIPTION
**Pull request by dkuegler**
Adds a flag flag and logic to keep/cast dtype of outvol to uchar (which also robustly rescales the intensities).

Fixes #461

### CODE REVIEW

**Comment by dkuegler** [comment]
@santiestrada32 can you check if this solves the situation with bias field correction in #459 ? The image looks fine to me.

`N4_bias_correct-py --in <file> --out <outfile> --threads 12 --uchar`

**Comment by m-reuter** [comment]
Also make sure that you adjust the places where this is called accordingly (in run_fastsurfer and in recon-surf).

**Comment by dkuegler** [comment]
Those places do not need to be adjusted because they are not affected. There, we do not use the outvol variable (bias field before wm normalization) which is the change here. The issue popped up, because for T2, WM normalization does not happen.

**Comment by m-reuter** [comment]
just thought that adding uchar flag there makes sense, given that we also want UCHAR output in those places? Even if it is the default but it will be easier to see?

**Comment by dkuegler** [comment]
I did not want to change the behavior where it was not necessary. I guess we have just changed that script in 2.2 so we can change the arguments again. But I am not really certain if there is ever a situation, where you would want the WM normalized image to not be UCHAR.

**Comment by santiestrada32** [comment]
I check the new changes in my dataset, and everything looks okay

**Pull request merged**
