### PR TITLE
Fix for PR 343, fix padding in interpolation tensor

### PR DESCRIPTION
**Pull request by dkuegler**
Addresses PR #343 

Fix bug in interpolation layer that did not pad the interpolated tensor, if scale_factor was all 1 and large padded images were passed

### CODE REVIEW

**Comment by dkuegler** [comment]
@ClePol can you please check, if this fixes your issues in training?

**Comment by ClePol** [comment]
yes, seems to be fixed

**Comment by m-reuter** [comment]
can this be merged? If so @dkuegler can you resolve conflicts and remove "draft" state? thanks

**Comment by dkuegler** [comment]
After that rebase, I'll have to do a quick sanity-check test to see, if it still works fine...

**Pull request merged**
