### PR TITLE
Bugfix: Wrong number of parameters for "setup_logging"

### PR DESCRIPTION
**Pull request by ClePol**
The function setup_logging expects one parameter, but two are given in train.py

### CODE REVIEW

**Comment by ClePol** [comment]
This bug also affects the stable branch

**Comment by LeHenschel** [comment]
Thanks for reporting this. Removing the argument in train.py does solve the error message, but then the log-file will not be set up correctly. In this case the cfg.LOG_DIR will be treated as the log-file and the command fails as well (because it is a directory, not a file). I would instead propose some changes to the logging function setup_logging @m-reuter

**Comment by ClePol** [comment]
I encountered this behavior as well - I think this can be circumvented by either specifying logfiles (instead of directories) in the .yml or modifying the setup_logging fucntion to work with directories and filenames. In my local copy I made a modification that appends the file ending 'log.txt' if the input is a directory.

If you agree, that this is good default behavior I can also add these modifications here.

**Comment by ClePol** [comment]
After looking more closely at your commit this is basically what you did as well. So I think that's a good solution.

**Comment by LeHenschel** [comment]
In the .yaml file there is only a LOG_DIR variable and this needs to be a directory as it is also used to set up the checkpoint, config, summary directories and so on. Appending log.txt is one option. With my commit, it is using the Experiment number as the filename (expr_${expr_num}.log). Can be changed to preference.

**Comment by ClePol** [comment]
I think changing back to two parameters might break the inference
https://github.com/ClePol/FastSurfer/blob/stable/FastSurferCNN/run_prediction.py#L337

I patched together a case handling that adresses both experiment number and directiory during training and then the full logfile path during inference - but this should probably be two different functions..

**Comment by LeHenschel** [comment]
We can also just roll back and join LOG DIR and EXPR_NUM in train.py and use the old setup_logging function. That is the easiest fix and given that david has multiple changes in his pull request the easiest for now.

So just replacing line 50 in train.py with:

```
logging.setup_logging(os.path.join(cfg.LOG_DIR, "logs", cfg.EXPR_NUM + ".log"))
```

**Pull request merged**
